### ISSUE TITLE
support gradle?

### ISSUE THREAD

**Issue by susemi99** [Aevi-UK/android-rxmessenger#21]
how to setup in build.gradle?

**Comment by andreas-borglin** [comment]
Hi @susemi99.

We have just updated the README and added a sample app. This should answer any questions you have. Otherwise feel free to open a new issue. Thanks

**Comment by susemi99** [comment]
`implementation "com.aevi.android:rxmessenger:<version>"`
I found latest version `2.0.1`. 

But `2.0.1` not have 
```java
public ObservableMessengerClient(Context context, ComponentName serviceComponentName) {
    this(context, serviceComponentName, null);
}
```


Thank you very much!

**Comment by brettwold** [comment]
Hi, sorry you caught us between releases. The README docs are for our v3.0.0 release which is now released. Enjoy

**Comment by susemi99** [comment]
Thank you!
It works well!!!
